# Generated by Django 2.0.2 on 2019-02-05 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190205_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 10, 49, 6, 565557, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
